### ISSUE TITLE
Repeated use of corral-double-quotes-x doesn't give greater nestings of quotes

### ISSUE THREAD

**Issue by squid-lee** [nivekuil/corral#3]
Some languages (python, scala) use triples quotes for verbatim quotes.
I'd like to be able to hit whatever bindings I have for corral-double-quotes-x (forward or backward) two more times and turn a singly quoted string into a triple quoted string. 

Even if that doesn't happen, I'd like it to fail gracefully, instead of leaving me with mismatched parenthesis.

Great library.

**Comment by nivekuil** [comment]
At the moment, corral only operates on one semantic expression per command. So while it's simple to have `"foobar"` become `"""foobar"""`, it's more difficult to have `"foo and bar"` become `"""foo and bar"""`.  If I understand you correctly, you want the behavior to be like this (calling corral-double-quotes-backward):
`"foo and b|ar"`
`"foo and "b|ar""`
`"foo "and b|ar""`
`""foo and b|ar""`
`"""foo and b|ar"""`
I think that this is definitely more useful than shifting to the previous quote (and breaking horribly if there isn't one), so I can take some time to see how this can be implemented.

Right now, the fastest way to turn a single quoted string into a triple quoted string with corral is to put the cursor at after end of the quote:
`"hello world"|`
and with `electric-pair-mode` or something like it enabled, `set-mark`, and in this case `backward-sexp`, and type a double quote
`"|"hello world""`
then `corral-double-quote-forward` will finish the job.

**Comment by nivekuil** [comment]
I'm closing this issue because while the stated behavior may be more convenient, there is no easy way to implement this in a consistent manner. A shift failure should be handled more gracefully now, and just moving the point directly outside of the sexp and calling a command should wrap the entire quoted area; another command in the opposite direction (or moving the point back by sexp first) will triple quote the string easily enough.
