### ISSUE TITLE
Corral can't handle hash. 

### ISSUE THREAD

**Issue by ReneFroger** [nivekuil/corral#4]
Thanks for sharing this awesome package with us! It's really appreciated. 

However, it seems there is a bug. For example, in the Jquery you have the following

`$(#id-of-foo-bar[])`

[] = pointer. 

Then I call the function `corral-double-quotes-backward`. Then it will wrap `id-of-foo-bar`. But when I call it again, it will not manage to expand it beyond the `#`. 
This is odd, because it behaves differently with 
`foo bar[]`. 

Then `bar` will be wrapped inside double quotes. Call `corral-double-quotes-backward` again, then it will wrap `foo bar`.

**Comment by nivekuil** [comment]
Thanks for the kind words, and for the bug report!

So the issue is that `#` is inherited as punctuation in javascript from cc-mode, so `backward-sexp` doesn't include it, and trying to use `backward-sexp` again when point is like this

`$(#[]id-of-foo-bar)`

Will throw an error. I think the best solution here is to either modify the syntax table of the mode directly through a global minor mode, or to have the user do it themselves. This won't work for selecting an element by id, though, like `$(.foo-bar)`, since you almost certainly want period to be punctuation. Unfortunately, emacs' mode-based syntax tables really fail when editing multiple languages in the same buffer. What do you think?

**Comment by ReneFroger** [comment]
Thanks for your reply! I'm relatively new to Elisp. But editing the syntax table of the mode sounds a good solution to me. Although I'm not sure how I could do it. 

Any suggestion?

**Comment by nivekuil** [comment]
I just added a custom syntax table for corral. You should be able to count # as a symbol by adding this after you load corral with the newest version:

(setq corral-syntax-rules '(?# "_"))

edit: actually, the implementation is still incomplete. It should work for only one rule, though.

**Comment by ReneFroger** [comment]
Thanks for your kind help. After updating it from MELPA and setting it in my init.el, it didn't worked out, When I'm home soon, I will make a gif to explain my situation.

**Comment by nivekuil** [comment]
The build on melpa is behind, but I think the latest commit should have it fully working now. Just copy the version from the repo and `(eval-buffer)`, and let me know how it goes. To set the rule you'll need to do this:

`(setq corral-syntax-entries '((?# "_")))`

You can also use 'add-to-list', like this:
`(add-to-list 'corral-syntax-entries '(?# "_"))`

The syntax for the rules is the same as `modify-syntax-entry`.

**Comment by ReneFroger** [comment]
It works now properly! :+1:.

By the way, Corral was the missing link in my editing workflow. I bound it to `C-;` and the Capslock behaves like Ctrl, editing text is a breeze now. Thanks for sharing this awesome package! :smile:.

**Comment by nivekuil** [comment]
Glad to hear it! Thanks for helping make this package better.
